# Generated by Django 3.2.14 on 2022-07-20 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movielist', '0002_auto_20220717_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screening',
            name='cinema',
        ),
        migrations.RemoveField(
            model_name='screening',
            name='movie',
        ),
        migrations.DeleteModel(
            name='Cinema',
        ),
        migrations.DeleteModel(
            name='Screening',
        ),
    ]
